#!/bin/sh

day=$(date +"%d")
year=$(date +"%y")
dir="y$year/d$day"

last_commit=$(git log -1 --format="%cd" --date="format:%y-%d")
if [ "$year-$day" = "$last_commit" ]; then
    echo "A commit for today already exists, quitting"
    exit 1
fi

echo "Removing instructions"
rm "$dir/site.html"
echo "Commiting solution"
git add "$dir"
git commit -m "20$year, day $day"
